name: Upload to Test PyPI on every commit to main

on:
  push:
    branches: [main]
    tags: ["*"]
  workflow_dispatch:

jobs:
  build-package:
    name: Build & inspect package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # for vcs tag-based versioning compatibility
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v2


  upload-to-test-pypi:
    name: Upload package to testPyPI
    needs: build-package
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing, but
      # should NOT be granted anywhere else!
      id-token: write

    steps:
      - name: Download packages built by build-and-inspect-python-package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
