name: Publish releases to PyPI

on:
  release:
    types:
      - published

jobs:
  build-package:
    name: Build & inspect package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # for vcs tag-based versioning compatibility
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v2

    # Upload to real PyPI on GitHub Releases.
  release-pypi:
    name: Publish released package to pypi.org
    needs: build-package
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing, but
      # should NOT be granted anywhere else!
      id-token: write

    steps:
      - name: Download packages built by build-and-inspect-python-package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
